"""
Seed data for a 10,000-note synthetic vault generator.

Pure data module — no generation logic. Exports:
  SEEDS          — list of project seed dicts
  NOISE_DOMAINS  — list of non-tech domain dicts for noise injection
  TIER_CONFIG    — dict mapping tier number to (min, max) note counts
"""

TIER_CONFIG = {
    1: (800, 1000),
    2: (200, 350),
    3: (50, 100),
    4: (10, 30),
}


SEEDS = [
    # ── Tier 1 — 3 projects, 800-1000 notes each ──

    {
        "name": "ecommerce-platform",
        "tier": 1,
        "tech_stack": ["React", "Next.js", "Stripe", "Postgres", "Redis", "Tailwind", "Prisma", "Vercel"],
        "description": "Full-stack e-commerce platform with checkout, inventory, and order management",
        "code_lang": "typescript",
        "tags": [
            "ecommerce", "checkout", "cart", "inventory", "orders", "payments",
            "catalog", "search", "shipping", "tax", "discounts", "wishlist",
            "analytics", "conversion", "fulfillment", "storefront", "admin",
            "products", "variants", "pricing", "subscriptions", "refunds",
        ],
        "title_words": [
            "checkout", "cart", "order", "product", "inventory", "payment",
            "shipping", "catalog", "discount", "wishlist", "storefront",
            "refund", "subscription", "pricing", "fulfillment", "search",
            "filter", "sort", "review", "rating", "variant", "SKU",
            "collection", "promotion", "coupon", "tax", "invoice",
        ],
        "vocab": [
            "checkout flow", "cart abandonment", "SKU", "inventory sync",
            "product catalog", "order fulfillment", "payment intent",
            "shipping rates", "tax calculation", "discount codes", "wishlist",
            "product variants", "search indexing", "A/B testing",
            "conversion funnel", "abandoned cart recovery", "stock keeping unit",
            "price rules", "gift cards", "order status", "return merchandise",
            "customer segments", "product recommendations", "cross-sell",
            "upsell", "average order value", "lifetime value", "churn rate",
            "storefront rendering", "headless commerce", "cart persistence",
            "session cart", "guest checkout", "address validation",
            "shipping zones", "flat rate shipping", "weight-based shipping",
            "real-time inventory", "backorder", "preorder", "out of stock",
            "low stock alert", "warehouse", "pick and pack", "packing slip",
            "tracking number", "carrier integration", "webhook notification",
            "idempotency key", "payment capture", "authorization hold",
            "partial refund", "store credit", "loyalty points",
            "dynamic pricing", "bulk discount", "tiered pricing",
        ],
    },

    {
        "name": "cloud-infra",
        "tier": 1,
        "tech_stack": ["Go", "Kubernetes", "Terraform", "Docker", "Prometheus", "Grafana", "Helm", "ArgoCD"],
        "description": "Cloud infrastructure platform with K8s orchestration, IaC, and observability",
        "code_lang": "go",
        "tags": [
            "kubernetes", "terraform", "infrastructure", "observability",
            "networking", "security", "scaling", "deployment", "monitoring",
            "alerting", "service-mesh", "ingress", "storage", "compute",
            "ci-cd", "gitops", "helm", "containers", "nodes", "clusters",
            "load-balancing", "dns",
        ],
        "title_words": [
            "cluster", "node", "pod", "service", "deployment", "ingress",
            "namespace", "configmap", "secret", "volume", "network",
            "policy", "autoscaler", "monitor", "alert", "dashboard",
            "terraform", "module", "pipeline", "rollout", "canary",
            "mesh", "proxy", "gateway", "certificate", "quota", "limit",
        ],
        "vocab": [
            "pod scheduling", "service mesh", "Istio", "Envoy",
            "cluster autoscaling", "node pools", "PVC",
            "ingress controller", "health probes", "circuit breaker",
            "canary deploy", "blue-green", "rollout", "HPA",
            "resource quota", "network policy", "RBAC", "service account",
            "persistent volume claim", "storage class", "CSI driver",
            "container runtime", "CRI", "OCI image", "registry mirror",
            "pod disruption budget", "node affinity", "taint toleration",
            "init container", "sidecar", "daemonset", "statefulset",
            "operator pattern", "custom resource definition", "admission webhook",
            "mutating webhook", "validating webhook", "kube-proxy", "CoreDNS",
            "etcd", "control plane", "kubelet", "scheduler", "API server",
            "Prometheus scrape", "PromQL", "Grafana dashboard",
            "alert manager", "recording rules", "SLO", "SLI", "error budget",
            "Terraform state", "remote backend", "module registry",
            "plan apply", "drift detection", "infrastructure as code",
        ],
    },

    {
        "name": "ml-pipeline",
        "tier": 1,
        "tech_stack": ["Python", "Spark", "Airflow", "BigQuery", "Docker", "TensorFlow", "MLflow", "dbt"],
        "description": "End-to-end ML pipeline with feature engineering, training, and batch inference",
        "code_lang": "python",
        "tags": [
            "ml", "pipeline", "data-engineering", "feature-store", "training",
            "inference", "orchestration", "data-quality", "experiments",
            "model-registry", "batch", "streaming", "etl", "analytics",
            "monitoring", "drift", "embeddings", "nlp", "gpu", "spark",
            "airflow", "bigquery",
        ],
        "title_words": [
            "pipeline", "model", "feature", "training", "inference",
            "experiment", "dataset", "embedding", "tokenizer", "DAG",
            "orchestrator", "drift", "metric", "evaluation", "batch",
            "stream", "transform", "schema", "lineage", "registry",
            "hyperparameter", "checkpoint", "GPU", "worker", "scheduler",
            "partition", "query",
        ],
        "vocab": [
            "feature engineering", "model training", "hyperparameter tuning",
            "data lineage", "DAG orchestration", "feature store",
            "model registry", "batch inference", "data drift",
            "A/B experiment", "embeddings", "tokenizer", "training loop",
            "GPU utilization", "learning rate", "loss function",
            "gradient descent", "backpropagation", "epoch", "mini-batch",
            "validation split", "cross-validation", "overfitting",
            "regularization", "dropout", "attention mechanism",
            "transformer architecture", "fine-tuning", "transfer learning",
            "ONNX export", "model serving", "latency budget",
            "throughput", "feature importance", "SHAP values",
            "confusion matrix", "precision recall", "F1 score", "ROC AUC",
            "data partition", "Spark job", "executor memory",
            "shuffle partition", "broadcast join", "window function",
            "Airflow sensor", "task dependency", "XCom", "trigger rule",
            "BigQuery slot", "partitioned table", "materialized view",
            "dbt model", "staging layer", "mart layer",
        ],
    },

    # ── Tier 2 — 8 projects, 200-350 notes each ──

    {
        "name": "mobile-app",
        "tier": 2,
        "tech_stack": ["React", "React Native", "Firebase", "Expo", "TypeScript", "Zustand"],
        "description": "Cross-platform mobile app with offline-first architecture and push notifications",
        "code_lang": "typescript",
        "tags": [
            "mobile", "react-native", "firebase", "expo", "offline",
            "push-notifications", "navigation", "animations", "state",
            "storage", "auth", "deep-links", "performance", "testing",
            "release", "codepush",
        ],
        "title_words": [
            "screen", "navigation", "component", "hook", "gesture",
            "animation", "notification", "storage", "sync", "auth",
            "camera", "location", "permission", "build", "release",
            "crash", "performance", "bundle", "splash", "deep-link",
        ],
        "vocab": [
            "native module", "bridge", "JSI", "Hermes engine",
            "Metro bundler", "Expo SDK", "EAS build", "OTA update",
            "stack navigator", "tab navigator", "deep linking",
            "push token", "FCM", "APNs", "background fetch",
            "AsyncStorage", "MMKV", "SQLite", "offline queue",
            "gesture handler", "reanimated", "shared element transition",
            "safe area", "keyboard avoiding", "flat list optimization",
            "virtualized list", "image caching", "CodePush",
            "crash reporting", "analytics event", "screen tracking",
            "app state", "foreground service", "biometric auth",
        ],
    },

    {
        "name": "realtime-messaging",
        "tier": 2,
        "tech_stack": ["Node.js", "WebSockets", "Redis", "TypeScript", "Socket.io", "RabbitMQ"],
        "description": "Real-time messaging platform with presence, typing indicators, and message history",
        "code_lang": "typescript",
        "tags": [
            "websockets", "redis", "realtime", "messaging", "presence",
            "channels", "pub-sub", "scaling", "delivery", "history",
            "moderation", "rate-limiting", "encryption", "threading",
            "reactions", "attachments",
        ],
        "title_words": [
            "channel", "message", "presence", "typing", "delivery",
            "notification", "thread", "reaction", "attachment", "room",
            "connection", "heartbeat", "reconnect", "broadcast", "queue",
            "subscriber", "publisher", "event", "socket", "stream",
        ],
        "vocab": [
            "WebSocket handshake", "socket upgrade", "ping pong frame",
            "connection pooling", "heartbeat interval", "reconnection backoff",
            "presence channel", "typing indicator", "read receipt",
            "message ordering", "causal consistency", "vector clock",
            "fan-out", "pub/sub", "channel subscription", "room membership",
            "message broker", "dead letter queue", "at-least-once delivery",
            "exactly-once semantics", "idempotent consumer", "message dedup",
            "Redis streams", "consumer group", "acknowledgment",
            "backpressure", "rate limiting", "sliding window",
            "connection limit", "horizontal scaling", "sticky sessions",
        ],
    },

    {
        "name": "ml-serving",
        "tier": 2,
        "tech_stack": ["Python", "PyTorch", "FastAPI", "Docker", "NVIDIA Triton", "Redis"],
        "description": "Low-latency ML model serving with batching, A/B testing, and model versioning",
        "code_lang": "python",
        "tags": [
            "ml", "pytorch", "fastapi", "serving", "inference",
            "batching", "versioning", "gpu", "optimization", "monitoring",
            "canary", "rollback", "benchmarking", "quantization",
            "caching", "load-balancing",
        ],
        "title_words": [
            "model", "endpoint", "batch", "inference", "latency",
            "throughput", "version", "canary", "rollback", "GPU",
            "quantize", "cache", "health", "benchmark", "profile",
            "tokenizer", "pipeline", "ensemble", "fallback", "timeout",
        ],
        "vocab": [
            "model artifact", "ONNX runtime", "TorchScript", "TensorRT",
            "dynamic batching", "request coalescing", "GPU memory pool",
            "CUDA stream", "mixed precision", "INT8 quantization",
            "model warm-up", "shadow deployment", "traffic splitting",
            "feature preprocessing", "input validation", "output schema",
            "model registry", "artifact store", "version pinning",
            "graceful degradation", "circuit breaker", "fallback model",
            "request queue", "priority scheduling", "SLA latency",
            "p50 p99 latency", "throughput benchmark", "load test",
            "GPU utilization", "memory fragmentation", "batch padding",
        ],
    },

    {
        "name": "content-cms",
        "tier": 2,
        "tech_stack": ["React", "Astro", "MDX", "Postgres", "Tailwind", "Cloudflare"],
        "description": "Headless CMS with MDX authoring, content versioning, and ISR rendering",
        "code_lang": "typescript",
        "tags": [
            "cms", "astro", "mdx", "content", "authoring", "versioning",
            "publishing", "media", "search", "localization", "templates",
            "permissions", "workflow", "preview", "seo", "rss",
        ],
        "title_words": [
            "content", "page", "template", "block", "media", "image",
            "author", "publish", "draft", "review", "version", "locale",
            "translation", "slug", "route", "sitemap", "feed", "search",
            "schema", "field", "collection",
        ],
        "vocab": [
            "content model", "structured content", "rich text field",
            "block editor", "MDX component", "frontmatter schema",
            "content versioning", "draft preview", "publish workflow",
            "scheduled publishing", "content localization", "i18n routing",
            "media library", "image optimization", "responsive images",
            "ISR revalidation", "static generation", "hybrid rendering",
            "SEO metadata", "Open Graph", "canonical URL", "sitemap XML",
            "RSS feed", "content API", "webhook trigger",
            "role-based access", "editorial workflow", "content migration",
            "slug generation", "collection schema", "reference field",
        ],
    },

    {
        "name": "payment-gateway",
        "tier": 2,
        "tech_stack": ["Go", "Stripe", "Postgres", "gRPC", "Kafka", "Vault"],
        "description": "PCI-compliant payment gateway with multi-provider routing and reconciliation",
        "code_lang": "go",
        "tags": [
            "payments", "stripe", "go", "pci", "reconciliation",
            "routing", "ledger", "webhooks", "retry", "idempotency",
            "fraud", "settlement", "refunds", "disputes", "compliance",
            "encryption",
        ],
        "title_words": [
            "payment", "charge", "refund", "dispute", "settlement",
            "ledger", "reconciliation", "webhook", "provider", "route",
            "retry", "idempotency", "fraud", "compliance", "encryption",
            "token", "vault", "payout", "transfer", "balance",
        ],
        "vocab": [
            "payment intent", "charge capture", "authorization hold",
            "idempotency key", "webhook signature", "event replay",
            "provider failover", "smart routing", "cost optimization",
            "interchange fee", "settlement batch", "reconciliation report",
            "double-entry ledger", "journal entry", "balance assertion",
            "PCI DSS", "tokenization vault", "card fingerprint",
            "3D Secure", "SCA", "fraud scoring", "velocity check",
            "chargeback", "dispute evidence", "representment",
            "payout schedule", "reserve hold", "currency conversion",
            "FX rate", "multi-currency", "cross-border fee",
        ],
    },

    {
        "name": "iot-platform",
        "tier": 2,
        "tech_stack": ["Terraform", "MQTT", "TimescaleDB", "Grafana", "Node.js", "InfluxDB"],
        "description": "IoT device management platform with telemetry ingestion and alerting",
        "code_lang": "typescript",
        "tags": [
            "iot", "mqtt", "timescaledb", "telemetry", "devices",
            "sensors", "alerting", "dashboards", "provisioning",
            "firmware", "edge", "gateway", "protocol", "data-retention",
            "downsampling", "geofencing",
        ],
        "title_words": [
            "device", "sensor", "telemetry", "gateway", "firmware",
            "provision", "alert", "threshold", "dashboard", "metric",
            "retention", "downsample", "protocol", "command", "shadow",
            "twin", "fleet", "OTA", "heartbeat", "geofence",
        ],
        "vocab": [
            "MQTT broker", "QoS level", "retained message", "last will",
            "topic hierarchy", "wildcard subscription", "device shadow",
            "digital twin", "device provisioning", "X.509 certificate",
            "fleet management", "firmware OTA", "edge computing",
            "gateway aggregation", "protocol translation", "CoAP bridge",
            "telemetry ingestion", "time-series compression",
            "continuous aggregate", "retention policy", "downsampling",
            "hypertable", "chunk interval", "compression ratio",
            "Grafana panel", "alert rule", "notification channel",
            "threshold breach", "anomaly detection", "geofence trigger",
        ],
    },

    {
        "name": "identity-provider",
        "tier": 2,
        "tech_stack": ["Postgres", "Redis", "Node.js", "SAML", "OIDC", "TypeScript"],
        "description": "Enterprise identity provider with SSO, MFA, and directory sync",
        "code_lang": "typescript",
        "tags": [
            "identity", "saml", "oidc", "auth", "sso", "mfa",
            "directory", "provisioning", "rbac", "sessions", "tokens",
            "federation", "compliance", "audit", "scim", "passwordless",
        ],
        "title_words": [
            "identity", "provider", "login", "session", "token",
            "SAML", "OIDC", "MFA", "directory", "sync", "role",
            "permission", "policy", "audit", "federation", "SSO",
            "password", "recovery", "enrollment", "consent",
        ],
        "vocab": [
            "SAML assertion", "identity provider", "service provider",
            "OIDC authorization code", "PKCE flow", "refresh token rotation",
            "JWT claims", "token introspection", "session fixation",
            "CSRF protection", "MFA enrollment", "TOTP", "WebAuthn",
            "FIDO2", "passkey", "password hashing", "Argon2", "bcrypt",
            "directory sync", "SCIM provisioning", "JIT provisioning",
            "RBAC policy", "attribute-based access", "consent screen",
            "OAuth scope", "audience validation", "issuer verification",
            "key rotation", "JWKS endpoint", "federation metadata",
        ],
    },

    {
        "name": "video-streaming",
        "tier": 2,
        "tech_stack": ["FFmpeg", "HLS", "S3", "CDN", "Go", "Postgres"],
        "description": "Video processing and streaming platform with adaptive bitrate and DRM",
        "code_lang": "go",
        "tags": [
            "video", "ffmpeg", "hls", "streaming", "transcoding",
            "cdn", "drm", "upload", "thumbnail", "subtitle",
            "analytics", "adaptive-bitrate", "live", "vod", "storage",
            "encoding",
        ],
        "title_words": [
            "video", "stream", "transcode", "encode", "upload",
            "thumbnail", "subtitle", "playlist", "segment", "manifest",
            "CDN", "origin", "cache", "DRM", "license", "player",
            "bitrate", "resolution", "codec", "container", "live",
        ],
        "vocab": [
            "FFmpeg pipeline", "H.264 encoding", "H.265 HEVC", "VP9",
            "AV1 codec", "adaptive bitrate", "HLS manifest", "DASH MPD",
            "segment duration", "GOP size", "keyframe interval",
            "two-pass encoding", "CRF quality", "bitrate ladder",
            "per-title encoding", "thumbnail sprite", "WebVTT subtitle",
            "CDN origin shield", "cache invalidation", "edge pop",
            "Widevine DRM", "FairPlay", "PlayReady", "license server",
            "content key", "signed URL", "token authentication",
            "live ingest", "RTMP push", "SRT protocol",
            "DVR window", "low-latency HLS", "chunked transfer",
        ],
    },

    # ── Tier 3 — 15 projects, 50-100 notes each ──

    {
        "name": "rust-cli-tool",
        "tier": 3,
        "tech_stack": ["Rust", "Clap", "Tokio", "Serde"],
        "description": "High-performance CLI tool with async I/O and structured output",
        "code_lang": "rust",
        "tags": ["rust", "cli", "async", "tooling", "performance", "binary"],
        "title_words": [
            "command", "argument", "parser", "output", "config",
            "error", "async", "binary", "install", "release",
        ],
        "vocab": [
            "clap derive", "subcommand", "argument parser", "anyhow error",
            "thiserror", "tokio runtime", "async main", "serde deserialize",
            "toml config", "crossterm", "tui framework", "indicatif progress",
            "colored output", "exit code", "stdin pipe", "stdout buffer",
            "signal handler", "graceful shutdown", "cargo release",
            "cross compilation", "musl target",
        ],
    },

    {
        "name": "chrome-extension",
        "tier": 3,
        "tech_stack": ["TypeScript", "Chrome APIs", "React", "Webpack"],
        "description": "Browser extension with content scripts, popup UI, and background workers",
        "code_lang": "typescript",
        "tags": ["chrome", "extension", "browser", "content-script", "popup", "manifest-v3"],
        "title_words": [
            "popup", "content-script", "background", "manifest",
            "permission", "storage", "message", "inject", "tab", "badge",
        ],
        "vocab": [
            "manifest v3", "service worker", "content script injection",
            "chrome.storage.local", "message passing", "port connection",
            "declarativeNetRequest", "side panel", "action popup",
            "context menu", "alarms API", "offscreen document",
            "cross-origin isolation", "CSP policy", "web accessible resource",
            "tab query", "active tab permission", "scripting API",
            "extension ID", "Chrome Web Store", "review process",
        ],
    },

    {
        "name": "slack-bot",
        "tier": 3,
        "tech_stack": ["Node.js", "Bolt", "TypeScript", "DynamoDB"],
        "description": "Slack bot with slash commands, interactive modals, and scheduled messages",
        "code_lang": "typescript",
        "tags": ["slack", "bot", "automation", "commands", "modals", "events"],
        "title_words": [
            "command", "modal", "event", "message", "block",
            "action", "shortcut", "workflow", "schedule", "webhook",
        ],
        "vocab": [
            "Bolt framework", "slash command", "block kit", "modal view",
            "interactive component", "action handler", "event subscription",
            "socket mode", "OAuth flow", "bot token", "user token",
            "app home", "rich text block", "section block", "input block",
            "overflow menu", "date picker", "multi-select",
            "scheduled message", "conversation history", "thread reply",
        ],
    },

    {
        "name": "graphql-gateway",
        "tier": 3,
        "tech_stack": ["TypeScript", "Apollo", "GraphQL", "Federation", "DataLoader"],
        "description": "GraphQL federation gateway stitching multiple subgraph services",
        "code_lang": "typescript",
        "tags": ["graphql", "federation", "gateway", "schema", "resolver", "subgraph"],
        "title_words": [
            "schema", "resolver", "query", "mutation", "subscription",
            "federation", "subgraph", "entity", "directive", "loader",
        ],
        "vocab": [
            "schema federation", "subgraph composition", "entity reference",
            "@key directive", "@extends", "rover CLI", "supergraph schema",
            "query planner", "DataLoader batching", "N+1 problem",
            "persisted queries", "automatic persisted queries", "query complexity",
            "depth limiting", "field-level auth", "custom scalar",
            "schema registry", "breaking change detection", "SDL first",
            "code-first schema", "subscription websocket",
        ],
    },

    {
        "name": "feature-flags",
        "tier": 3,
        "tech_stack": ["Go", "Redis", "gRPC", "OpenFeature"],
        "description": "Feature flag service with targeting rules, gradual rollouts, and audit trail",
        "code_lang": "go",
        "tags": ["feature-flags", "targeting", "rollout", "experiments", "toggles", "sdk"],
        "title_words": [
            "flag", "targeting", "rule", "segment", "rollout",
            "experiment", "variant", "override", "audit", "SDK",
        ],
        "vocab": [
            "feature toggle", "boolean flag", "multivariate flag",
            "targeting rule", "user segment", "percentage rollout",
            "kill switch", "flag dependency", "evaluation context",
            "OpenFeature provider", "client-side SDK", "server-side SDK",
            "flag lifecycle", "stale flag detection", "audit log",
            "change history", "environment promotion", "flag archival",
            "local override", "test harness",
        ],
    },

    {
        "name": "email-service",
        "tier": 3,
        "tech_stack": ["Node.js", "SendGrid", "Handlebars", "SQS", "TypeScript"],
        "description": "Transactional and marketing email service with templates and delivery tracking",
        "code_lang": "typescript",
        "tags": ["email", "sendgrid", "templates", "delivery", "bounce", "analytics"],
        "title_words": [
            "template", "campaign", "delivery", "bounce", "open",
            "click", "unsubscribe", "suppression", "sender", "domain",
        ],
        "vocab": [
            "transactional email", "marketing campaign", "email template",
            "Handlebars partial", "dynamic content", "merge tag",
            "delivery rate", "bounce handling", "soft bounce", "hard bounce",
            "spam score", "SPF record", "DKIM signature", "DMARC policy",
            "sender reputation", "IP warm-up", "suppression list",
            "unsubscribe link", "CAN-SPAM", "open tracking pixel",
            "click tracking", "SendGrid webhook",
        ],
    },

    {
        "name": "search-service",
        "tier": 3,
        "tech_stack": ["Elasticsearch", "TypeScript", "Node.js", "Kibana"],
        "description": "Full-text search service with faceted filtering, autocomplete, and relevance tuning",
        "code_lang": "typescript",
        "tags": ["search", "elasticsearch", "indexing", "relevance", "autocomplete", "facets"],
        "title_words": [
            "index", "query", "filter", "facet", "autocomplete",
            "suggest", "analyzer", "mapping", "relevance", "boost",
        ],
        "vocab": [
            "inverted index", "BM25 scoring", "TF-IDF", "analyzer chain",
            "custom tokenizer", "edge ngram", "completion suggester",
            "fuzzy matching", "synonym filter", "stopword list",
            "field mapping", "nested object", "parent-child join",
            "aggregation bucket", "terms facet", "range facet",
            "function score", "decay function", "boosting query",
            "multi-match", "cross-field search", "index alias",
            "reindex API", "scroll search", "search-after pagination",
        ],
    },

    {
        "name": "analytics-dashboard",
        "tier": 3,
        "tech_stack": ["React", "D3.js", "ClickHouse", "TypeScript", "Recharts"],
        "description": "Real-time analytics dashboard with custom visualizations and drill-down",
        "code_lang": "typescript",
        "tags": ["analytics", "dashboard", "visualization", "charts", "metrics", "reporting"],
        "title_words": [
            "chart", "metric", "dimension", "filter", "drill-down",
            "widget", "layout", "export", "schedule", "threshold",
        ],
        "vocab": [
            "time-series chart", "bar chart", "pie chart", "scatter plot",
            "heatmap", "funnel visualization", "cohort analysis",
            "dimension grouping", "metric aggregation", "custom formula",
            "dashboard layout", "widget grid", "date range picker",
            "comparison period", "drill-down path", "cross-filter",
            "CSV export", "scheduled report", "PDF snapshot",
            "real-time refresh", "ClickHouse materialized view",
            "approximate count", "HyperLogLog",
        ],
    },

    {
        "name": "webhook-relay",
        "tier": 3,
        "tech_stack": ["Go", "Postgres", "Redis", "NATS"],
        "description": "Webhook delivery service with retry, fan-out, and delivery verification",
        "code_lang": "go",
        "tags": ["webhooks", "delivery", "retry", "fan-out", "events", "reliability"],
        "title_words": [
            "webhook", "endpoint", "delivery", "retry", "payload",
            "signature", "filter", "transform", "log", "replay",
        ],
        "vocab": [
            "webhook registration", "endpoint verification",
            "HMAC signature", "payload schema", "content negotiation",
            "exponential backoff", "retry budget", "dead letter",
            "fan-out delivery", "event filter", "payload transform",
            "delivery log", "replay mechanism", "rate limiting",
            "circuit breaker", "timeout policy", "bulk replay",
            "event sourcing", "idempotency header", "delivery status",
        ],
    },

    {
        "name": "rate-limiter",
        "tier": 3,
        "tech_stack": ["Go", "Redis", "Lua", "gRPC"],
        "description": "Distributed rate limiting service with sliding window and token bucket algorithms",
        "code_lang": "go",
        "tags": ["rate-limiting", "distributed", "redis", "algorithm", "throttling", "quota"],
        "title_words": [
            "limiter", "window", "bucket", "quota", "policy",
            "override", "key", "counter", "response", "header",
        ],
        "vocab": [
            "sliding window", "fixed window", "token bucket",
            "leaky bucket", "sliding window log", "sliding window counter",
            "Redis Lua script", "atomic increment", "TTL expiry",
            "rate limit header", "retry-after", "quota allocation",
            "burst allowance", "global rate limit", "per-user limit",
            "per-IP limit", "distributed counter", "clock skew",
            "rate limit key", "override policy",
        ],
    },

    {
        "name": "config-management",
        "tier": 3,
        "tech_stack": ["Go", "etcd", "gRPC", "Protobuf"],
        "description": "Centralized configuration management with versioning, validation, and live reload",
        "code_lang": "go",
        "tags": ["config", "management", "versioning", "validation", "reload", "etcd"],
        "title_words": [
            "config", "version", "schema", "validate", "reload",
            "namespace", "override", "history", "diff", "rollback",
        ],
        "vocab": [
            "configuration schema", "JSON Schema validation",
            "environment override", "namespace hierarchy",
            "config versioning", "diff viewer", "rollback mechanism",
            "live reload", "watch stream", "etcd lease",
            "key prefix", "config snapshot", "migration script",
            "default values", "secret reference", "interpolation",
            "feature gate", "A/B config", "gradual rollout",
            "config audit log",
        ],
    },

    {
        "name": "log-aggregator",
        "tier": 3,
        "tech_stack": ["Go", "Kafka", "Elasticsearch", "Fluentd"],
        "description": "Centralized log aggregation with structured logging, search, and alerting",
        "code_lang": "go",
        "tags": ["logging", "aggregation", "kafka", "search", "alerting", "structured"],
        "title_words": [
            "log", "collector", "pipeline", "parser", "filter",
            "index", "search", "alert", "retention", "archive",
        ],
        "vocab": [
            "structured logging", "log level", "JSON log format",
            "Fluentd input plugin", "Kafka topic partition",
            "log pipeline", "grok parser", "regex extraction",
            "field enrichment", "GeoIP lookup", "log sampling",
            "index lifecycle", "hot-warm-cold architecture",
            "retention policy", "log archive", "S3 glacier",
            "search query DSL", "log-based alert", "anomaly detection",
            "correlation ID", "trace context",
        ],
    },

    {
        "name": "secrets-manager",
        "tier": 3,
        "tech_stack": ["Go", "Vault", "Postgres", "gRPC"],
        "description": "Secret management service with rotation, access control, and audit logging",
        "code_lang": "go",
        "tags": ["secrets", "vault", "rotation", "access-control", "encryption", "audit"],
        "title_words": [
            "secret", "key", "rotation", "policy", "access",
            "audit", "encrypt", "decrypt", "lease", "mount",
        ],
        "vocab": [
            "secret engine", "KV store", "dynamic secret",
            "lease duration", "automatic rotation", "rotation policy",
            "transit encryption", "envelope encryption", "master key",
            "unseal key", "Shamir secret sharing", "access policy",
            "ACL token", "identity entity", "audit device",
            "response wrapping", "cubbyhole", "namespace isolation",
            "secret versioning", "soft delete",
        ],
    },

    {
        "name": "notification-hub",
        "tier": 3,
        "tech_stack": ["Node.js", "TypeScript", "Postgres", "Redis", "Firebase"],
        "description": "Multi-channel notification hub with templates, preferences, and delivery tracking",
        "code_lang": "typescript",
        "tags": ["notifications", "push", "email", "sms", "in-app", "preferences"],
        "title_words": [
            "notification", "channel", "template", "preference",
            "delivery", "digest", "schedule", "category", "priority", "batch",
        ],
        "vocab": [
            "notification channel", "push notification", "in-app message",
            "email notification", "SMS gateway", "Twilio integration",
            "notification template", "variable interpolation",
            "user preference", "opt-out", "quiet hours",
            "digest aggregation", "batch delivery", "priority queue",
            "delivery status", "read tracking", "notification center",
            "category subscription", "frequency capping", "A/B content",
        ],
    },

    {
        "name": "api-gateway",
        "tier": 3,
        "tech_stack": ["Go", "Envoy", "gRPC", "OpenAPI"],
        "description": "API gateway with rate limiting, auth, request transformation, and versioning",
        "code_lang": "go",
        "tags": ["api", "gateway", "routing", "auth", "rate-limiting", "versioning"],
        "title_words": [
            "route", "upstream", "middleware", "auth", "transform",
            "version", "rate-limit", "cors", "cache", "circuit-breaker",
        ],
        "vocab": [
            "request routing", "path-based routing", "header-based routing",
            "upstream service", "load balancing", "health check",
            "request transformation", "response transformation",
            "API key validation", "JWT verification", "OAuth proxy",
            "CORS policy", "request size limit", "timeout policy",
            "circuit breaker", "retry policy", "API versioning",
            "deprecation header", "OpenAPI spec", "request logging",
        ],
    },

    # ── Tier 4 — 30 projects, 10-30 notes each ──

    {
        "name": "sqlite-cache",
        "tier": 4,
        "tech_stack": ["Python", "SQLite", "Click"],
        "description": "Local SQLite-backed cache layer with TTL and LRU eviction",
        "code_lang": "python",
        "tags": ["cache", "sqlite", "ttl", "eviction"],
        "title_words": ["cache", "eviction", "TTL", "entry", "lookup", "purge"],
        "vocab": [
            "LRU eviction", "TTL expiry", "cache hit ratio",
            "WAL mode", "journal mode", "PRAGMA optimize",
            "prepared statement", "connection pool", "cache warming",
            "size limit", "eviction policy", "cache invalidation",
        ],
    },

    {
        "name": "csv-parser",
        "tier": 4,
        "tech_stack": ["Rust", "Serde"],
        "description": "Streaming CSV parser with custom delimiters and type inference",
        "code_lang": "rust",
        "tags": ["csv", "parser", "streaming", "data"],
        "title_words": ["parser", "column", "row", "delimiter", "header", "type"],
        "vocab": [
            "streaming parser", "byte reader", "field delimiter",
            "quote escaping", "header detection", "type inference",
            "column mapping", "row iterator", "error recovery",
            "encoding detection", "BOM handling", "line terminator",
        ],
    },

    {
        "name": "markdown-renderer",
        "tier": 4,
        "tech_stack": ["TypeScript", "unified", "remark", "rehype"],
        "description": "Markdown-to-HTML renderer with custom syntax extensions",
        "code_lang": "typescript",
        "tags": ["markdown", "renderer", "html", "syntax"],
        "title_words": ["renderer", "plugin", "syntax", "node", "transform", "output"],
        "vocab": [
            "AST node", "remark plugin", "rehype transform",
            "syntax extension", "custom directive", "code fence",
            "frontmatter parsing", "table alignment", "footnote",
            "task list", "autolink", "heading ID",
        ],
    },

    {
        "name": "url-shortener",
        "tier": 4,
        "tech_stack": ["Go", "Redis", "Postgres"],
        "description": "URL shortening service with analytics and custom aliases",
        "code_lang": "go",
        "tags": ["url", "shortener", "redirect", "analytics"],
        "title_words": ["link", "redirect", "alias", "click", "expiry", "stat"],
        "vocab": [
            "base62 encoding", "collision detection", "custom alias",
            "redirect chain", "click analytics", "referrer tracking",
            "geolocation", "link expiry", "rate limiting",
            "vanity URL", "QR code", "UTM parameter",
        ],
    },

    {
        "name": "cron-scheduler",
        "tier": 4,
        "tech_stack": ["Python", "APScheduler", "Redis"],
        "description": "Distributed cron scheduler with job persistence and failure recovery",
        "code_lang": "python",
        "tags": ["cron", "scheduler", "jobs", "distributed"],
        "title_words": ["job", "schedule", "trigger", "worker", "retry", "history"],
        "vocab": [
            "cron expression", "interval trigger", "date trigger",
            "job store", "misfire policy", "coalesce", "max instances",
            "job lock", "distributed lock", "execution history",
            "failure callback", "retry backoff",
        ],
    },

    {
        "name": "image-resizer",
        "tier": 4,
        "tech_stack": ["Go", "libvips", "S3"],
        "description": "On-the-fly image resizing service with caching and format conversion",
        "code_lang": "go",
        "tags": ["image", "resize", "processing", "cdn"],
        "title_words": ["image", "resize", "crop", "format", "cache", "quality"],
        "vocab": [
            "image pipeline", "resize operation", "crop gravity",
            "format conversion", "WebP encoding", "AVIF support",
            "quality parameter", "progressive JPEG", "strip metadata",
            "signed URL", "cache header", "origin fetch",
        ],
    },

    {
        "name": "pdf-generator",
        "tier": 4,
        "tech_stack": ["Node.js", "Puppeteer", "Handlebars"],
        "description": "HTML-to-PDF generation service with templates and header/footer support",
        "code_lang": "typescript",
        "tags": ["pdf", "generator", "template", "html"],
        "title_words": ["pdf", "template", "page", "header", "footer", "margin"],
        "vocab": [
            "Puppeteer page", "PDF options", "page size", "margin config",
            "header template", "footer template", "page number",
            "print media query", "font embedding", "image rendering",
            "table pagination", "landscape orientation",
        ],
    },

    {
        "name": "queue-worker",
        "tier": 4,
        "tech_stack": ["Python", "Celery", "Redis", "RabbitMQ"],
        "description": "Background job processing with priority queues and dead letter handling",
        "code_lang": "python",
        "tags": ["queue", "worker", "celery", "background-jobs"],
        "title_words": ["task", "queue", "worker", "retry", "priority", "dead-letter"],
        "vocab": [
            "task queue", "worker pool", "prefetch count",
            "task routing", "priority queue", "dead letter exchange",
            "task retry", "exponential backoff", "result backend",
            "chord", "chain", "group",
        ],
    },

    {
        "name": "health-checker",
        "tier": 4,
        "tech_stack": ["Go", "Prometheus", "HTTP"],
        "description": "Service health check aggregator with configurable probes and status pages",
        "code_lang": "go",
        "tags": ["health", "monitoring", "probes", "status"],
        "title_words": ["probe", "check", "status", "endpoint", "alert", "uptime"],
        "vocab": [
            "health endpoint", "liveness probe", "readiness probe",
            "TCP check", "HTTP check", "gRPC health", "check interval",
            "timeout threshold", "consecutive failures", "status page",
            "incident timeline", "uptime percentage",
        ],
    },

    {
        "name": "dns-resolver",
        "tier": 4,
        "tech_stack": ["Rust", "Tokio", "trust-dns"],
        "description": "Async DNS resolver with caching, DNSSEC validation, and DoH support",
        "code_lang": "rust",
        "tags": ["dns", "resolver", "caching", "network"],
        "title_words": ["resolver", "record", "cache", "query", "zone", "upstream"],
        "vocab": [
            "DNS query", "A record", "AAAA record", "CNAME resolution",
            "recursive resolver", "iterative query", "cache TTL",
            "negative caching", "DNSSEC validation", "RRSIG",
            "DNS over HTTPS", "DNS over TLS",
        ],
    },

    {
        "name": "file-watcher",
        "tier": 4,
        "tech_stack": ["Rust", "notify", "Tokio"],
        "description": "Cross-platform file system watcher with debouncing and glob filtering",
        "code_lang": "rust",
        "tags": ["filesystem", "watcher", "events", "cross-platform"],
        "title_words": ["watcher", "event", "path", "filter", "debounce", "recursive"],
        "vocab": [
            "inotify", "FSEvents", "ReadDirectoryChangesW",
            "debounce interval", "glob filter", "recursive watch",
            "rename detection", "event coalescing", "symlink follow",
            "ignore pattern", "hot reload", "change batch",
        ],
    },

    {
        "name": "git-hooks",
        "tier": 4,
        "tech_stack": ["Bash", "Node.js", "husky"],
        "description": "Git hooks manager with pre-commit linting, commit message validation, and CI checks",
        "code_lang": "typescript",
        "tags": ["git", "hooks", "pre-commit", "linting"],
        "title_words": ["hook", "pre-commit", "commit-msg", "lint", "format", "validate"],
        "vocab": [
            "pre-commit hook", "commit-msg hook", "pre-push hook",
            "husky install", "lint-staged", "conventional commit",
            "commitlint", "staged files", "hook bypass",
            "parallel execution", "hook timeout", "exit code",
        ],
    },

    {
        "name": "env-validator",
        "tier": 4,
        "tech_stack": ["TypeScript", "Zod", "dotenv"],
        "description": "Environment variable validator with schema definition and type-safe access",
        "code_lang": "typescript",
        "tags": ["env", "validation", "schema", "config"],
        "title_words": ["env", "schema", "validate", "default", "required", "type"],
        "vocab": [
            "env schema", "Zod validation", "dotenv loading",
            "required variable", "default value", "type coercion",
            "enum constraint", "URL format", "port range",
            "env prefix", "secret masking", "validation error",
        ],
    },

    {
        "name": "schema-migrator",
        "tier": 4,
        "tech_stack": ["Go", "Postgres", "SQLite"],
        "description": "Database schema migration tool with up/down migrations and version tracking",
        "code_lang": "go",
        "tags": ["migration", "schema", "database", "versioning"],
        "title_words": ["migration", "schema", "version", "up", "down", "rollback"],
        "vocab": [
            "migration file", "version table", "up migration",
            "down migration", "migration lock", "dirty state",
            "checksum validation", "sequential ordering",
            "transaction wrapping", "DDL statement", "data migration",
            "zero-downtime migration",
        ],
    },

    {
        "name": "load-tester",
        "tier": 4,
        "tech_stack": ["Go", "Vegeta", "Prometheus"],
        "description": "HTTP load testing tool with configurable scenarios and real-time metrics",
        "code_lang": "go",
        "tags": ["load-testing", "performance", "benchmarking", "http"],
        "title_words": ["scenario", "target", "rate", "duration", "result", "report"],
        "vocab": [
            "request rate", "constant pacer", "ramp-up period",
            "target URL", "request body", "header injection",
            "latency histogram", "percentile", "error rate",
            "connection reuse", "HTTP/2 support", "result export",
        ],
    },

    {
        "name": "mock-server",
        "tier": 4,
        "tech_stack": ["TypeScript", "Express", "OpenAPI"],
        "description": "Mock API server auto-generated from OpenAPI specs with request validation",
        "code_lang": "typescript",
        "tags": ["mock", "server", "openapi", "testing"],
        "title_words": ["mock", "endpoint", "response", "fixture", "delay", "scenario"],
        "vocab": [
            "OpenAPI spec", "mock response", "fixture file",
            "request validation", "response delay", "error simulation",
            "dynamic mock", "stateful mock", "record mode",
            "proxy fallback", "schema validation", "example generation",
        ],
    },

    {
        "name": "proxy-service",
        "tier": 4,
        "tech_stack": ["Go", "net/http", "TLS"],
        "description": "Reverse proxy with TLS termination, header rewriting, and connection pooling",
        "code_lang": "go",
        "tags": ["proxy", "reverse-proxy", "tls", "routing"],
        "title_words": ["proxy", "upstream", "route", "header", "tls", "pool"],
        "vocab": [
            "reverse proxy", "TLS termination", "SNI routing",
            "header rewrite", "X-Forwarded-For", "connection pool",
            "keepalive", "upstream health", "load balancing",
            "round robin", "least connections", "proxy protocol",
        ],
    },

    {
        "name": "retry-handler",
        "tier": 4,
        "tech_stack": ["TypeScript", "axios"],
        "description": "Configurable retry handler with backoff strategies and jitter",
        "code_lang": "typescript",
        "tags": ["retry", "resilience", "backoff", "http"],
        "title_words": ["retry", "backoff", "jitter", "policy", "attempt", "delay"],
        "vocab": [
            "exponential backoff", "linear backoff", "full jitter",
            "equal jitter", "decorrelated jitter", "max retries",
            "retry condition", "status code filter", "timeout abort",
            "circuit breaker integration", "retry budget", "backoff cap",
        ],
    },

    {
        "name": "circuit-breaker-lib",
        "tier": 4,
        "tech_stack": ["Go", "Prometheus"],
        "description": "Circuit breaker library with half-open probing and metric export",
        "code_lang": "go",
        "tags": ["circuit-breaker", "resilience", "fault-tolerance", "library"],
        "title_words": ["breaker", "state", "threshold", "probe", "reset", "metric"],
        "vocab": [
            "closed state", "open state", "half-open state",
            "failure threshold", "success threshold", "timeout duration",
            "probe request", "state transition", "error counter",
            "sliding window", "metric export", "fallback handler",
        ],
    },

    {
        "name": "event-bus",
        "tier": 4,
        "tech_stack": ["TypeScript", "RxJS"],
        "description": "In-process event bus with typed channels, filtering, and replay",
        "code_lang": "typescript",
        "tags": ["events", "bus", "pub-sub", "reactive"],
        "title_words": ["event", "channel", "subscriber", "filter", "replay", "buffer"],
        "vocab": [
            "event channel", "typed event", "subscriber callback",
            "event filter", "replay buffer", "hot observable",
            "cold observable", "backpressure", "unsubscribe",
            "wildcard subscription", "event history", "dead letter",
        ],
    },

    {
        "name": "task-runner",
        "tier": 4,
        "tech_stack": ["Python", "Click", "TOML"],
        "description": "Project task runner with dependency graph, parallel execution, and file targets",
        "code_lang": "python",
        "tags": ["tasks", "runner", "automation", "build"],
        "title_words": ["task", "target", "dependency", "run", "parallel", "watch"],
        "vocab": [
            "task definition", "dependency graph", "topological sort",
            "parallel execution", "file target", "timestamp check",
            "task cache", "environment variable", "working directory",
            "shell command", "task group", "default task",
        ],
    },

    {
        "name": "changelog-gen",
        "tier": 4,
        "tech_stack": ["TypeScript", "conventional-changelog"],
        "description": "Changelog generator from conventional commits with release grouping",
        "code_lang": "typescript",
        "tags": ["changelog", "release", "conventional-commits", "semver"],
        "title_words": ["changelog", "release", "commit", "version", "group", "format"],
        "vocab": [
            "conventional commit", "commit parser", "release group",
            "semver bump", "breaking change", "feature commit",
            "fix commit", "changelog template", "tag detection",
            "monorepo support", "scope filter", "header format",
        ],
    },

    {
        "name": "dep-checker",
        "tier": 4,
        "tech_stack": ["Node.js", "TypeScript", "npm-registry"],
        "description": "Dependency vulnerability and freshness checker with policy enforcement",
        "code_lang": "typescript",
        "tags": ["dependencies", "security", "audit", "freshness"],
        "title_words": ["dependency", "vulnerability", "update", "policy", "audit", "lock"],
        "vocab": [
            "vulnerability scan", "CVE database", "severity level",
            "dependency tree", "transitive dependency", "lockfile audit",
            "version policy", "allowed license", "deprecated package",
            "update strategy", "major bump", "security advisory",
        ],
    },

    {
        "name": "lint-rules",
        "tier": 4,
        "tech_stack": ["TypeScript", "ESLint", "AST"],
        "description": "Custom ESLint rules with AST visitors and auto-fix support",
        "code_lang": "typescript",
        "tags": ["lint", "eslint", "rules", "ast"],
        "title_words": ["rule", "visitor", "node", "fix", "report", "schema"],
        "vocab": [
            "AST visitor", "rule schema", "message ID",
            "auto-fix", "suggestion", "rule tester",
            "selector syntax", "scope analysis", "type information",
            "shared settings", "rule category", "recommended config",
        ],
    },

    {
        "name": "perf-profiler",
        "tier": 4,
        "tech_stack": ["Rust", "perf", "flamegraph"],
        "description": "Performance profiler with flame graph generation and hotspot detection",
        "code_lang": "rust",
        "tags": ["profiling", "performance", "flamegraph", "analysis"],
        "title_words": ["profile", "flamegraph", "hotspot", "trace", "sample", "report"],
        "vocab": [
            "CPU profile", "wall-clock time", "sampling interval",
            "stack trace", "flame graph", "hotspot function",
            "call tree", "allocation profiling", "memory leak",
            "instruction cache", "branch prediction", "perf event",
        ],
    },

    {
        "name": "api-client-gen",
        "tier": 4,
        "tech_stack": ["TypeScript", "OpenAPI", "Zod"],
        "description": "Type-safe API client generator from OpenAPI specs with runtime validation",
        "code_lang": "typescript",
        "tags": ["codegen", "openapi", "client", "type-safe"],
        "title_words": ["client", "endpoint", "schema", "type", "generate", "validate"],
        "vocab": [
            "OpenAPI parser", "code generator", "endpoint method",
            "request schema", "response schema", "Zod validator",
            "type inference", "discriminated union", "error type",
            "pagination helper", "auth interceptor", "base URL config",
        ],
    },

    {
        "name": "db-seeder",
        "tier": 4,
        "tech_stack": ["Python", "Faker", "SQLAlchemy"],
        "description": "Database seeder with realistic fake data and relationship-aware generation",
        "code_lang": "python",
        "tags": ["seeder", "faker", "database", "test-data"],
        "title_words": ["seed", "factory", "fixture", "relationship", "fake", "generate"],
        "vocab": [
            "Faker provider", "factory pattern", "seed file",
            "relationship graph", "foreign key", "unique constraint",
            "bulk insert", "transaction batch", "deterministic seed",
            "locale support", "custom provider", "data cleanup",
        ],
    },

    {
        "name": "log-parser",
        "tier": 4,
        "tech_stack": ["Rust", "regex", "Serde"],
        "description": "Structured log parser with pattern matching and JSON output",
        "code_lang": "rust",
        "tags": ["log", "parser", "regex", "structured"],
        "title_words": ["parser", "pattern", "field", "timestamp", "level", "output"],
        "vocab": [
            "log format", "grok pattern", "regex capture group",
            "timestamp parsing", "level extraction", "JSON output",
            "multiline merge", "continuation pattern", "field mapping",
            "custom format", "syslog parsing", "Apache combined",
        ],
    },

    {
        "name": "metric-exporter",
        "tier": 4,
        "tech_stack": ["Go", "Prometheus", "OpenTelemetry"],
        "description": "Metric collection and export bridge between Prometheus and OpenTelemetry",
        "code_lang": "go",
        "tags": ["metrics", "prometheus", "opentelemetry", "export"],
        "title_words": ["metric", "counter", "gauge", "histogram", "exporter", "collector"],
        "vocab": [
            "counter metric", "gauge metric", "histogram bucket",
            "summary quantile", "metric label", "cardinality",
            "scrape endpoint", "push gateway", "OTLP exporter",
            "metric naming", "unit suffix", "metric description",
        ],
    },

    {
        "name": "snapshot-tester",
        "tier": 4,
        "tech_stack": ["TypeScript", "Jest", "Vitest"],
        "description": "Snapshot testing utilities with inline snapshots and custom serializers",
        "code_lang": "typescript",
        "tags": ["snapshot", "testing", "serializer", "diff"],
        "title_words": ["snapshot", "serializer", "update", "diff", "inline", "matcher"],
        "vocab": [
            "snapshot file", "inline snapshot", "custom serializer",
            "snapshot update", "diff algorithm", "property matcher",
            "asymmetric matcher", "snapshot resolver", "CI protection",
            "deterministic output", "date serializer", "pretty format",
        ],
    },
]


NOISE_DOMAINS = [
    {
        "name": "cooking",
        "display": "Cooking & Recipes",
        "vocab": [
            "mise en place", "julienne cut", "deglaze pan", "fond",
            "mirepoix", "roux", "beurre blanc", "sear", "braise",
            "blanch", "temper chocolate", "emulsify", "fold batter",
            "proof dough", "caramelize onions", "chiffonade",
            "brunoise", "bain-marie", "reduction sauce",
        ],
    },
    {
        "name": "gardening",
        "display": "Gardening & Horticulture",
        "vocab": [
            "companion planting", "crop rotation", "hardiness zone",
            "soil pH", "compost tea", "mulch layer", "drip irrigation",
            "deadheading", "transplant shock", "root bound",
            "nitrogen fixation", "raised bed", "succession planting",
            "cold frame", "seed stratification", "pollinator garden",
            "cover crop", "green manure",
        ],
    },
    {
        "name": "fitness",
        "display": "Fitness & Training",
        "vocab": [
            "progressive overload", "compound movement", "isolation exercise",
            "rep range", "time under tension", "AMRAP", "EMOM",
            "deload week", "periodization", "hypertrophy",
            "VO2 max", "lactate threshold", "heart rate zone",
            "mobility work", "foam rolling", "active recovery",
            "RPE scale", "one rep max",
        ],
    },
    {
        "name": "photography",
        "display": "Photography",
        "vocab": [
            "aperture priority", "shutter speed", "ISO sensitivity",
            "depth of field", "bokeh", "golden hour", "exposure triangle",
            "histogram", "RAW processing", "white balance",
            "focal length", "prime lens", "composition rule of thirds",
            "leading lines", "negative space", "bracketing",
            "long exposure", "flash sync",
        ],
    },
    {
        "name": "woodworking",
        "display": "Woodworking",
        "vocab": [
            "dovetail joint", "mortise and tenon", "dado cut",
            "rabbet joint", "grain direction", "wood movement",
            "board foot", "rough sawn", "planer thickness",
            "router template", "chisel bevel", "hand plane",
            "table saw fence", "miter gauge", "dust collection",
            "finish coat", "polyurethane",
        ],
    },
    {
        "name": "knitting",
        "display": "Knitting & Fiber Arts",
        "vocab": [
            "cast on", "bind off", "knit stitch", "purl stitch",
            "stockinette", "garter stitch", "ribbing", "cable pattern",
            "lace knitting", "yarn weight", "gauge swatch",
            "blocking", "seaming", "circular needle",
            "double-pointed needle", "short rows", "yarn over",
        ],
    },
    {
        "name": "birdwatching",
        "display": "Birdwatching & Ornithology",
        "vocab": [
            "field marks", "plumage", "molt cycle", "song pattern",
            "call note", "raptor kettle", "migration flyway",
            "habitat type", "breeding range", "wintering grounds",
            "life list", "big year", "pishing", "birding by ear",
            "scope digiscoping", "ebird hotspot",
        ],
    },
    {
        "name": "pottery",
        "display": "Pottery & Ceramics",
        "vocab": [
            "wheel throwing", "centering clay", "wedging",
            "bisque fire", "glaze fire", "cone temperature",
            "kiln schedule", "oxidation firing", "reduction firing",
            "slip casting", "coil building", "slab construction",
            "trimming foot", "glaze chemistry", "crawling defect",
            "pinholing", "underglazing",
        ],
    },
    {
        "name": "origami",
        "display": "Origami & Paper Folding",
        "vocab": [
            "valley fold", "mountain fold", "crease pattern",
            "base form", "bird base", "waterbomb base", "sink fold",
            "petal fold", "reverse fold", "squash fold",
            "wet folding", "modular origami", "tessellation",
            "kami paper", "foil paper", "crimp fold",
        ],
    },
    {
        "name": "calligraphy",
        "display": "Calligraphy & Lettering",
        "vocab": [
            "nib angle", "thick thin stroke", "ascender line",
            "descender line", "baseline", "x-height", "serif",
            "sans-serif", "italic hand", "copperplate script",
            "brush pen", "ink viscosity", "letter spacing",
            "flourishing", "ligature", "blackletter",
        ],
    },
    {
        "name": "fermentation",
        "display": "Fermentation & Preserving",
        "vocab": [
            "lacto-fermentation", "wild yeast", "starter culture",
            "brine concentration", "airlock", "pH measurement",
            "Kahm yeast", "pellicle", "secondary fermentation",
            "carbonation level", "kombucha SCOBY", "kefir grains",
            "sauerkraut", "kimchi paste", "fermentation vessel",
            "temperature control",
        ],
    },
    {
        "name": "sourdough",
        "display": "Sourdough Baking",
        "vocab": [
            "sourdough starter", "levain build", "autolyse",
            "bulk fermentation", "stretch and fold", "coil fold",
            "shaping tension", "bench rest", "cold retard",
            "banneton proof", "scoring blade", "ear formation",
            "crumb structure", "hydration percentage", "baker's math",
            "oven spring",
        ],
    },
    {
        "name": "espresso",
        "display": "Espresso & Coffee",
        "vocab": [
            "extraction yield", "grind size", "dose weight",
            "brew ratio", "channeling", "puck prep", "WDT tool",
            "tamping pressure", "pre-infusion", "pressure profiling",
            "shot time", "crema", "milk steaming", "microfoam",
            "latte art", "single origin", "light roast",
        ],
    },
    {
        "name": "vinyl-records",
        "display": "Vinyl Records & Hi-Fi",
        "vocab": [
            "turntable setup", "cartridge alignment", "tracking force",
            "anti-skate", "phono preamp", "RIAA equalization",
            "record cleaning", "surface noise", "inner groove distortion",
            "pressing quality", "dead wax", "matrix number",
            "first pressing", "reissue", "gatefold sleeve",
            "audiophile grade",
        ],
    },
    {
        "name": "board-games",
        "display": "Board Games & Tabletop",
        "vocab": [
            "worker placement", "engine building", "deck building",
            "area control", "action points", "victory points",
            "resource management", "tile laying", "drafting mechanic",
            "push your luck", "cooperative play", "legacy campaign",
            "rulebook errata", "BGG ranking", "solo variant",
            "player count sweet spot",
        ],
    },
    {
        "name": "beekeeping",
        "display": "Beekeeping & Apiculture",
        "vocab": [
            "hive inspection", "brood pattern", "queen cell",
            "swarm prevention", "varroa mite", "mite count",
            "honey super", "wax foundation", "frame spacing",
            "smoker technique", "nectar flow", "dearth period",
            "winter cluster", "sugar syrup feed", "pollen patty",
            "hive beetle",
        ],
    },
    {
        "name": "bread-baking",
        "display": "Bread Baking",
        "vocab": [
            "windowpane test", "proofing temperature", "instant yeast",
            "active dry yeast", "preferment", "poolish", "biga",
            "tangzhong", "enriched dough", "laminated dough",
            "steam injection", "Dutch oven", "baking stone",
            "internal temperature", "crumb shot", "crust color",
        ],
    },
    {
        "name": "cheese-making",
        "display": "Cheese Making",
        "vocab": [
            "rennet coagulation", "curd cutting", "whey drainage",
            "salting", "pressing weight", "affinage cave",
            "mold ripening", "washed rind", "bloomy rind",
            "aging temperature", "humidity control", "calcium chloride",
            "mesophilic culture", "thermophilic culture", "cheese cloth",
            "brine solution",
        ],
    },
    {
        "name": "flower-arranging",
        "display": "Flower Arranging & Floristry",
        "vocab": [
            "focal flower", "filler flower", "greenery",
            "mechanics", "floral foam", "chicken wire armature",
            "spiral technique", "hand-tied bouquet", "cascading design",
            "color harmony", "texture contrast", "stem conditioning",
            "hydration tube", "proportion rule", "negative space",
            "seasonal availability",
        ],
    },
    {
        "name": "soap-making",
        "display": "Soap Making",
        "vocab": [
            "cold process", "hot process", "saponification",
            "lye calculator", "superfat percentage", "trace stage",
            "fragrance oil", "essential oil blend", "natural colorant",
            "mold release", "gel phase", "cure time",
            "INS value", "cleansing value", "conditioning value",
            "swirl technique",
        ],
    },
    {
        "name": "candle-making",
        "display": "Candle Making",
        "vocab": [
            "wax melt point", "soy wax", "beeswax blend",
            "wick size", "wick centering", "fragrance load",
            "hot throw", "cold throw", "cure period",
            "mushrooming", "tunneling", "wet spots",
            "container candle", "pillar candle", "pour temperature",
            "burn test",
        ],
    },
    {
        "name": "aquarium",
        "display": "Aquarium & Fishkeeping",
        "vocab": [
            "nitrogen cycle", "ammonia spike", "nitrite conversion",
            "beneficial bacteria", "water change", "substrate layer",
            "planted tank", "CO2 injection", "lighting spectrum",
            "fish compatibility", "schooling behavior", "breeding tank",
            "quarantine tank", "protein skimmer", "canister filter",
            "water parameters",
        ],
    },
    {
        "name": "hiking",
        "display": "Hiking & Backpacking",
        "vocab": [
            "trail blaze", "switchback", "cairn marker",
            "elevation gain", "contour line", "topographic map",
            "leave no trace", "ten essentials", "layering system",
            "base weight", "resupply point", "water purification",
            "bear canister", "trekking pole", "blister prevention",
            "summit push",
        ],
    },
    {
        "name": "astronomy",
        "display": "Astronomy & Stargazing",
        "vocab": [
            "apparent magnitude", "right ascension", "declination",
            "celestial equator", "light pollution", "Bortle scale",
            "telescope aperture", "eyepiece magnification", "star hopping",
            "Messier catalog", "deep sky object", "planetary nebula",
            "globular cluster", "meteor shower radiant", "opposition",
            "conjunction",
        ],
    },
    {
        "name": "watercolor",
        "display": "Watercolor Painting",
        "vocab": [
            "wet on wet", "wet on dry", "graded wash",
            "flat wash", "granulation", "blooming", "lifting paint",
            "masking fluid", "glazing layer", "color temperature",
            "palette mixing", "brush loading", "paper buckling",
            "cold press paper", "hot press paper", "value study",
        ],
    },
]
